version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3344:3344"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./flask-api
      dockerfile: Dockerfile
    ports:
      - "5545:5545"
    environment:
      - NODE_ENV=development
      - GEMINI_KEY=${GEMINI_KEY}
      - GEMINI_URL=${GEMINI_URL}
    volumes:
      - ./flask-api:/app
      - /app/node_modules  # Add this to avoid overwriting node_modules with the mounted volume
